### ISSUE TITLE
Current game API endpoint

### ISSUE THREAD

**Issue by TomClancyIsDead** [bayvakoof/civstats-app#1]
I'm not sure if this is where you'd like issues for the website itself. If there is a better place, please tell me.

http://civstats.bayvakoof.com/@id/current should link to the http://civstats.bayvakoof.com/players/@id/games/@game_id

This will allow for a nightbot command that links to the civstats dashboard page for viewers that'd rather refresh that page than spam the commands in chat, as well as get the demos chart.

**Comment by bayvakoof** [comment]
Added this, http://civstats.bayvakoof.com/@id/current-game points to the user's current or most recent game. @id/current-game.txt is kind of redundant but i still made it anyway :D.
